stages:
- name: Build & Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: my-image/blog:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: ccr.ccs.tencentyun.com
- name: Deploy
  steps:
  - runScriptConfig:
      image: alpine/git
      shellScript: |-
        curl -k -u ${TOKEN} \
        -X PUT \
        -H 'Accept: application/json' \
        -H 'Content-Type: application/json' \
        -d '{"containers":[{"image":"ccr.ccs.tencentyun.com/my-image/blog:'${CICD_EXECUTION_SEQUENCE}'","name":"blog"}]}' \
        "${DEPLOYMENT_API}"
    envFrom:
    - sourceName: deploy
      sourceKey: TOKEN
    - sourceName: deploy
      sourceKey: DEPLOYMENT_API
- name: Sync
  steps:
  - runScriptConfig:
      image: alpine/git
      shellScript: |-
        git remote -v
        git remote add github https://github.com/samsarapt/samsarapt.github.io.git
        git push -f github master
timeout: 60
notification: {}
